from typing import Any

class PipelineState:
    stage: Any
    phase: Any
    def __init__(self, name: str, depth: int): ...
    def init(self, is_producer: bool = ...) -> None: ...
    def move_to_next_stage(self) -> None: ...

class TMABar:
    def __init__(self, pool: Any, depth: int, name: str): ...
    def init(self, count: int) -> None: ...
    def wait(self, stage: Any, phase: Any) -> None: ...
    def arrive(self, stage: Any, bytes: int) -> None: ...
    def ptr_to(self, stage: list[int]) -> Any:
        """
        ptr_to([0]) gets pointer to the 0th element.
        """
        ...
    def remote_view(self, cta_id: Any) -> Any: ...

class TCGen05Bar:
    def __init__(self, pool: Any, depth: int, name: str): ...
    def init(self, count: int) -> None: ...
    def wait(self, stage: Any, phase: Any) -> None: ...
    def arrive(self, stage: Any, cta_group: int = ..., cta_mask: Any = ...) -> None: ...
    def ptr_to(self, stage: list[int]) -> Any:
        """
        ptr_to([0]) gets pointer to the 0th element.
        """
        ...

class MBarrier:
    def __init__(self, pool: Any, depth: int, name: str): ...
    def init(self, count: int) -> None: ...
    def wait(self, stage: Any, phase: Any) -> None: ...
    def arrive(self, stage: Any, cta_id: Any = ..., pred: Any = ...) -> None: ...
    def ptr_to(self, stage: list[int]) -> Any:
        """
        ptr_to([0]) gets pointer to the 0th element.
        """
        ...
