from typing import Any

class ClusterPersistentScheduler2D:
    def __init__(self, *args, **kwargs):
        self.m_idx = ...
        self.n_idx = ...
        ...

    def init(self, bx: Any): ...
    def valid(self): ...
    def next_tile(self): ...
